server:
  port: 9005

spring:
  application:
    name: API-GATEWAY-SERVICE

  config:
    import: configserver:http://localhost:9007  # Add a spring.config.import=configserver: property or To disable this check, set spring.cloud.config.enabled=false

hystrix:
  command:
  fallbackcmd:
  execution:
      isolation:
        thread:
          timeoutInMillisecond: 10000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
